In [1]:
from keras.datasets import mnist

# 훈련 세트, 테스트 세트
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

Using TensorFlow backend.


In [2]:
train_images.shape

(60000, 28, 28)

In [3]:
len(train_images)

60000

In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
test_images.shape

(10000, 28, 28)

In [6]:
len(test_images)

10000

In [7]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [8]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [9]:
network.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_2 (Dense)              (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


In [10]:
# 손실함수 loss function : 훈련데이터에서 신경망의 성능을 측정하는 방법으로 네트워크가 옳은 방향으로 학습될 수 있도록 도와준다
# 옵티마이저 optimizer : 입력된 데이터와 손실 함수를 기반으로 네트워크를 업데이트하는 메커니즘
# 훈련과 테스트 과정을 모니터링할 지표 : 여기서는 정확도(정확히 분류된 이미지의 비율)만 고려
network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [11]:
# 이미지 데이터를 네트워크에 맞도록 모든 값을 0과 1 사이로 스케일을 조정
# 훈련 이미지는 [0, 255] 사이의 값인 uint8타입의 (60000, 28, 28) 크기의ㅣ 배열
# 이 데이터를 0과 1 사이의 값을 가지는 float32 타입의 (60000, 28, 28) 크기의 배열로 바꾼다.
train_images = train_images.reshape((60000, 28* 28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28* 28))
test_images = test_images.astype('float32') / 255

In [12]:
train_images.shape

(60000, 784)

In [13]:
# 레이블 준비
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [14]:
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [15]:
# 훈련데이터에 모델을 학습시킨다
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 4s 75us/step - loss: 0.2567 - acc: 0.9251
Epoch 2/5
60000/60000 [==============================] - 5s 76us/step - loss: 0.1033 - acc: 0.9690
Epoch 3/5
60000/60000 [==============================] - 4s 74us/step - loss: 0.0683 - acc: 0.9796
Epoch 4/5
60000/60000 [==============================] - 4s 73us/step - loss: 0.0494 - acc: 0.9848
Epoch 5/5
60000/60000 [==============================] - 5s 76us/step - loss: 0.0376 - acc: 0.9886


In [16]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 0s 50us/step


In [17]:
print('test_acc:', test_acc)

test_acc: 0.98
